steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/order-dashboard', '-f', 'src/dashboard/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/order-dashboard']
images:
  - 'gcr.io/$PROJECT_ID/order-dashboard'
